accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

homeo/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "homeo"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.RemedyView.as_view(), name="remedy"),
    path("<int:pk>/materia/", views.MateriaView.as_view(), name="materia"),
]

miniproject4AStaggenborg/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='homeo:index')),
    path('homeo/', include('homeo.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

homeo/models.py
import datetime

from django.db import models
from django.contrib import admin
from django.utils import timezone


class PotencyList(models.Model):
    availablePotency = models.CharField(max_length=5)

    def __str__(self):
        return self.availablePotency


class MateriaMedica(models.Model):
    link = models.URLField()
    data = models.TextField()
    description = models.CharField(max_length=100, default="")

    def __str__(self):
        return self.description


class Remedy(models.Model):
    name = models.CharField(max_length=50)

    potency = models.ManyToManyField(PotencyList)
    materiaMedica = models.ManyToManyField(MateriaMedica)

    def __str__(self):
        return self.name

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

homeo/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .models import Remedy, MateriaMedica


class RemedyView(generic.DetailView):
    """remedy view"""
    model = Remedy
    template_name = "homeo/remedy.html"


class MateriaView(generic.DetailView):
    """materia medica view"""
    model = MateriaMedica
    template_name = "homeo/materia.html"


def index(request):
    """index page"""
    """check to see if the search box was used."""
    if request.GET.get("query") is not None:
        q = request.GET.get("query")
        r = Remedy.objects.select_related().filter(name__startswith=q)
    else:
        q = ""
        r = Remedy.objects.select_related().all()

    return render(request, "homeo/index.html", {"remedy_list": r, "query": q})


def remedy(request, remedy_id):
    """lookup remedy by id"""
    r = get_object_or_404(Remedy, pk=remedy_id)
    return render(request, "homeo/remedy.html", {"remedy": r})


def materia(request, materia_id):
    """lookup materia media by id"""
    m = get_object_or_404(MateriaMedica, pk=materia_id)
    return render(request, "homeo/materia.html", {"materia": m})

homeo/templates/base.html
{% load static %}
<!doctype html>
<head>
    <title>{% block title %}{% endblock %} - miniproject4AStaggenborg</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homeo/style.css' %}">
    <meta name="theme-color" content="#712cf9">
    {% block head %}{%  endblock %}
</head>

<body>
    <nav class="p-3 text-bg-dark">
      <h1><a class="navbar-brand" href="/homeo">Homeopathic Remedy Catalog</a></h1>
      <ul>
        {% if user.is_authenticated %}
            <li><span class="text-nowrap">Welcome, {{ user.get_username }}</span></li>
            <li><a href="{% url 'logout' %}?next={{ request.path }}" class="btn btn-outline-light me-1 text-nowrap" role="button">Log Out</a></li>
            <li><a href="/admin" class="btn btn-warning me-1"><img src="{% static 'homeo/images/gear-24px.png' %}"></a></li>
        {% else %}
            <li><a href="{% url 'signup' %}" class="btn btn-outline-light me-1" role="button">Register</a></li>
            <li><a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-outline-light me-1" role="button">Log In</a></li>
        {% endif %}
          <li><button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#aboutModal"><img src="{% static 'homeo/images/info-24px.png' %}"></button></li>
      </ul>
    </nav>
    <div class="modal fade" id="aboutModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">About</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            miniproject4 for INF601 by Adam Staggenborg.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <section class="content">
      <header>
        {% block header %}{% endblock %}
      </header>

      {% block content %}{% endblock %}
    </section>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

homeo/templates/homeo/index.html
{% extends 'base.html' %}

{% block header %}
<h2>{% block title %}Available Remedies{% endblock %}</h2>
    <form class="d-flex" role="search" method="get">
        <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="query" value={{ query }}>
        <button class="btn btn-outline-success me-1" type="submit">Search</button>
        {% if query != "" %}
            <a class="btn btn-outline-danger" role="button" href="/homeo">X</a>
        {% endif %}
    </form>
{#  {% if g.user %}#}
{#  <a href="" class="btn btn-info" role="button">Add New</a>#}
{#  {% endif %}#}
{% endblock %}
{% block content %}
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr scope="row">
          <th scope="col" class="text-center">Remedy</th>
          <th scope="col" class="text-center">Available Potencies</th>
          <th scope="col" class="text-center">Available Materia Medicas</th>
          <th scope="col" class="text-center"></th>
        </tr>
    </thead>
    <tbody>
    {% for r in remedy_list %}
      <tr scope="row">
        <td class="col">{{ r.name }}</td>
        <td class="col">
            {% for i, p in r.potency.values_list %}
                {% if not forloop.last %}
                    {{ p }},
                {% endif %}

                {% if forloop.last %}
                    {{ p }}
                {% endif %}
            {% endfor %}
        </td>
        <td class="col text-center">{{ r.materiaMedica.count }} Available
{#            <a class="btn btn-info" href="{% url 'homeo:materia' r.id %}">View</a>#}
        </td>
        <td class="col text-center"><a class="btn btn-info btn-sm" href="{% url 'homeo:remedy' r.id %}">View Remedy</a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

homeo/templates/homeo/materia.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %}{{ materiamedica.description }} {% endblock %}</h2>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="ext-link"> External Link: <a href="{{ materiamedica.link }}" target="_blank">{{ materiamedica.link }}</a></div>
        <div>Viewer:</div>
        <iframe srcdoc="{{ materiamedica.data }}" style="width: 900px; height: 600px; border: none; padding: 0; margin: 0;"></iframe>
    </div>

{% endblock %}

homeo/templates/homeo/remedy.html
{% extends 'base.html' %}

{% block header %}
    <h2>{% block title %} {{ remedy.name }} {% endblock %}</h2>
    <h5>
        {% for i, p in remedy.potency.values_list %}
            {% if not forloop.last %}
                {{ p }},
            {% endif %}

            {% if forloop.last %}
                {{ p }}
            {% endif %}
        {% endfor %}
    </h5>
{% endblock %}
{% block content %}
    <div class="container">
        <h4>Materia Medica List:</h4>
        {% for id, link, data, desc in remedy.materiaMedica.values_list %}
            <div class="row p-1">
                <div class="col-auto">{{ desc }}</div>
                <div class="col-auto"><a class="btn btn-info btn-sm" href="{% url "homeo:materia" id %}" target="_blank">View</a> <a class="btn btn-secondary btn-sm" href="{{ link }}" target="_blank">View (External)</a></div>
            </div>
        {% endfor %}
    </div>
{% endblock %}